php/basket.php, php/connectdb.php, php/database.php, php/tests.php
Connectdb.php
- Small Quality of life changes, including making local/ server connections easier to switch between, making feedback messages on connection
Database.php
- Small Quality of life changes, including adjusting SQL datatypes, keywords etc
Tests.php
- Created test data for the SQL tables: Role, Users, Product, ProductType, Products
- Created examples for inserting in these and searching amongst other tables -> to be used in other backend pages as a reference
Basket.php
- Started the backend for the basket page
- Created basic session variables and condition statements to output to user incase of user not being logged in/ basket being empty
-Created foundation for connecting to the database and displaying all items in the session 2D array $basketItems, which should hold all …
=> Safa - Backend Database Tests, Backend Basket and Quality of Life Changes

php/basket.php, php/database.php, php/tests.php
Database.php:
- Changing slight SQL phrases to make readability, using the database and inputting easier
Tests.php
- Created tests, conditions and debugging echo statements for: -->Orders Table, OrderItems Table, TicketType Table, SupportTickets, Returns
- Need to come back to Return Table - May have to split up or adjust the attributes of table
-Need to fix date problems
=> Database Quality of Life and Tests.php progress

css/products.css
Improved the look of product and category pages and made pages mobile friendly
=> Updated CSS

basket.html, php/products.php, products/bubblegum.html
-Wrote comments for basket.html's JS for readability
- Created products.php to handle the functionality of adding products to the basket
- Created a form in the bubblegum.html product page to send product info to the products.php page
=> Basket Functionality

basket.html, index.html
Issues with repeated navbar and missing css lines were causing the basket issues. Fixed those and adjusted small issues in index.html regarding repeated lines and incorrect naming
=> Fixed Basket's Navbar Issue

Checkout.html, categories/Mice.html, css/aboutus.css, css/contact.css, css/fonts.css, css/signin.css, index.html, profile.html
- Removing irrelevant fonts
- Creating Font CSS file
- Linking index.html to this
=> Starting Font Changes

basket.html, php/basketChanges.php, php/products.php, signin.html, signup.html
- Completely fixed basket error -> was mistakenly treating as an associative array when it was a numerical array - so changed to associative array for usability
- Basket now makes permanent changes to the basket session variable!
- Also fixed the css of the sign in and sign up pages
=> Fixing Basket Completely! :)

contact.html, php/contactForm.php, php/database.php, php/profile.php, profile.html
Minor changes to other issues that were spotted during todays meeting
=> Contact us fix

js/searchBar.js, php/basketStart.php, php/connectdb.php, php/contactForm.php, php/previousOrders.php, php/products.php, php/profile.php, profile.html
Spent the entire night on this fixing things up
Changes:
- Deleted Uneeded SQL comments in my php files
- Profile page now displays the users information upon loading in
- Managed to get the order history to actually work and showing important information about the users past orders
Previous commits also involved:
- Changing how data is collected in the contact form and removing uneeded js variables
- Changing the search bar so its able to be used in nested folders e.g. product pages
=> Profile, contact us, and search bar fixed

basket.html, php/basketStart.php
=> Basket page UID to Username

php/database.php
Adding comments, making a check for the products rather than automatically adding products.
=> Edits to database creation file

php/database.php
=> Fixing data types

php/database.php
=> Updating comments

php/database.php
=> Reviews table php

php/database.php
- Create the table -Populate the table
=> Accesskeys database changes

css/navbar.css, index.html, php/basketNumber.php
Basket number feature in index page
=> Basket number index page

php/profile.php, profile.html
Now works through outputting a php header instead of a redirect string
=> Profile redirect fixed

signin.html
=> Add remember me checkbox

php/rememberMe.php, php/signInFunction.php, php/signOutFunction.php
Cookies now add the correct future date to the db rather than 0
=> Cookies Date Issue

php/profile.php, php/signInFunction.php, php/signOutFunction.php
Clearing cookie in database and session accurately - fixed issue where it didn't clear up
=> Cookie Destruction

php/previousOrders.php
All I needed to do was remove the test code luckily
=> Fixed previous orders only taking user 1

contact.html
No longer redirects to a separate page
=> Contact page submission confirmation

php/database.php, php/guestAccount.php, php/placeOrder.php
Main functionality of having guest orders complete!
Based on if ur a guest or a customer, the system processes ur order differently. Need to make sure info is being pulled from the checkout page - make it so it only asks name etc if you're not logged in becvause its a bit repetitivbe
=> Guest Functionality

categories/Headphones.html, categories/Keyboards.html, categories/Mice.html, categories/Mousepads.html, categories/monitors.html, categories/products.html, php/database.php
Clicking buy takes you to the product's page
=> Fixing product buttons

php/database.php
Done as its own merge as database.php is prone to merge conflicts
=> pinnedReviewID added to products table

Checkout.html, checkoutSummary.html, php/checkoutSummary.php, php/placeOrder.php
- tried making order form details add to the database but idk it's not working. theres an issue with the form results not being sent to the form for some reason. if that gets fixed it will work.
=> order form details adding to database attempt

inventory.html
Changed background colour as footer looked strange.
=> Inventory Management page

adminPages/userTransactionPage.html, php/database.php, php/placeOrder.php, php/userTransaction.php
- database changes
- changes to checkout system (status and amount to database)
- usertransaction php changes to grab database stuff -usertransaction html changes
=> UserTransactionPt1

adminPages/userTransactionPage.html, php/adminCheck.php, php/updateStatus.php
Make alerts for changing status
=> User transaction Status frontend alert system

adminPages/adminupdate.html, adminPages/adminuser.html, adminPages/customer-review.html, adminPages/inventory.html, adminPages/review-details.html, adminPages/ticket.html, adminPages/userTransactionPage.html, css/adminNavbar.css
=> Made admin navbar a css file and put it in every admin page,

css/products.css
Font was too difficult to read especially the numbers
=> Updated Fonts on Product pages

categories/products.html, js/productsFilter.js
Filter and Search now fully functional
=> Updated Products Filter
